# Generated by Django 3.2.13 on 2022-07-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='experiencepoint',
            name='text',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='keyskill',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
